apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels: 
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: allen13/helloworld:v0.1
